Use the new virtual environment in composing script

diff --git a/compose b/compose
--- a/compose
+++ b/compose
@@ -4,3 +4,84 @@
 # Licensed under the Effective Elegy Licence
 
 set -e
+
+readonly COMPOSER_NAME="Couplet Composer"
+readonly ODE_NAME="Obliging Ode"
+readonly ANTHEM_NAME="Unsung Anthem"
+
+echo "Running the shell script wrapper for $COMPOSER_NAME, the build utility \
+of $ODE_NAME and $ANTHEM_NAME"
+echo "$COMPOSER_NAME will be run in composing mode"
+
+readonly PRESET_MODE_ARGUMENT="preset"
+readonly COMPOSE_MODE_ARGUMENT="compose"
+
+readonly COMPOSER_EXECUTABLE_NAME="couplet-composer"
+
+# Set the current directory to the correct root while setting the directory
+# constants.
+
+current_working_directory=$PWD
+
+cd ..
+
+echo "The working directory is set to $PWD"
+
+readonly BUILD_DIRECTORY_NAME="build"
+readonly BUILD_DIRECTORY="$PWD/$BUILD_DIRECTORY_NAME"
+
+cd $current_working_directory
+
+echo "The working directory is set to $PWD"
+
+# See if the directory generated by configuring mode is in place.
+
+exit_for_missing_configuration() {
+  echo "The build directory wasn't found; please make sure to run the \
+cofiguring script before attempting to build Obliging Ode and Unsung \
+Anthem" 1>&2
+  exit 1
+}
+
+if [ ! -d "$BUILD_DIRECTORY" ]; then
+  echo "The directory $BUILD_DIRECTORY is missing"
+  exit_for_missing_configuration
+fi
+
+# Set up Couplet Composer.
+
+current_directory="${0%/*}"
+current_working_directory=$PWD
+
+$current_directory/util/set_up "$@"
+
+# Change back to the directory of this script to prevent the set-up script from
+# messing up the working directory.
+
+cd $current_working_directory
+echo "The working directory is set to $PWD"
+
+# Switch to the correct directory.
+cd ..
+
+echo "The working directory is set to $PWD"
+
+# Run Couplet Composer.
+
+preset_mode=false
+
+for arg in "$@"; do
+  if [ "$arg" = "$PRESET_MODE_ARGUMENT" ]; then
+    preset_mode=true
+  fi
+done
+
+source $PWD/env/bin/activate
+
+if [ "$preset_mode" = true ]; then
+  $COMPOSER_EXECUTABLE_NAME "$@" $COMPOSE_MODE_ARGUMENT
+else
+  $COMPOSER_EXECUTABLE_NAME $COMPOSE_MODE_ARGUMENT "$@"
+fi
+
+deactivate
